### ISSUE TITLE
Loading `active_record/base` results in "uninitialized constant ActiveModel::Validations::PresenceValidator"

### ISSUE THREAD

**Issue by donv** [ruboto/JRuby9K_POC#6]
This is triggered by the "Setup simple" button in the "ACTIVERECORD" activity:

```
I/System.out: Setup simple sqlite database
I/System.out: require 'active_record'
I/zygote: Background concurrent copying GC freed 208835(7MB) AllocSpace objects, 7(140KB) LOS objects, 17% free, 27MB/33MB, paused 1.085ms total 175.055ms
I/zygote: Background concurrent copying GC freed 147641(5MB) AllocSpace objects, 42(852KB) LOS objects, 16% free, 29MB/35MB, paused 942us total 173.864ms
I/zygote: Background concurrent copying GC freed 173360(6MB) AllocSpace objects, 48(972KB) LOS objects, 16% free, 30MB/36MB, paused 688us total 148.100ms
I/zygote: Do full code cache collection, code=1471KB, data=983KB
I/zygote: After code cache collection, code=1242KB, data=761KB
I/zygote: Background concurrent copying GC freed 192510(7MB) AllocSpace objects, 36(716KB) LOS objects, 16% free, 31MB/37MB, paused 650us total 102.411ms
I/System.out: defineClass: name: json.ext.Parser$INVOKER$s$0$1$newInstance
I/System.out: defineClass: name: json.ext.Parser$INVOKER$i$0$1$initialize
I/System.out: defineClass: name: json.ext.Parser$INVOKER$i$0$0$parse
I/System.out: defineClass: name: json.ext.Parser$INVOKER$i$0$0$source_get
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$s$1$0$from_state
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$1$0$buffer_initial_length_set
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$0$0$indent_get
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$1$0$indent_set
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$0$0$max_nesting_get
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$0$0$object_nl_get
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$0$0$space_get
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$1$0$array_nl_set
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$0$0$to_h
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$0$0$array_nl_get
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$0$0$check_circular_p
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$0$0$buffer_initial_length_get
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$1$0$initialize_copy
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$2$0$op_aset
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$1$0$space_before_set
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$1$0$generate
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$1$0$op_aref
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$1$0$space_set
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$1$0$object_nl_set
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$1$0$configure
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$1$0$max_nesting_set
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$1$0$depth_set
I/zygote: Do partial code cache collection, code=1470KB, data=952KB
I/zygote: After code cache collection, code=1468KB, data=952KB
    Increasing code cache capacity to 4MB
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$0$0$depth_get
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$0$0$ascii_only_p
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$0$1$initialize
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$0$0$allow_nan_p
I/zygote: Background concurrent copying GC freed 207356(10MB) AllocSpace objects, 1(32KB) LOS objects, 16% free, 30MB/36MB, paused 931us total 137.222ms
I/System.out: defineClass: name: json.ext.GeneratorState$INVOKER$i$0$0$space_before_get
I/System.out: defineClass: name: json.ext.GeneratorMethods$RbArray$INVOKER$s$0$0$to_json
I/System.out: defineClass: name: json.ext.GeneratorMethods$RbFalse$INVOKER$s$0$0$to_json
I/System.out: defineClass: name: json.ext.GeneratorMethods$RbFloat$INVOKER$s$0$0$to_json
I/System.out: defineClass: name: json.ext.GeneratorMethods$RbHash$INVOKER$s$0$0$to_json
I/System.out: defineClass: name: json.ext.GeneratorMethods$RbInteger$INVOKER$s$0$0$to_json
I/System.out: defineClass: name: json.ext.GeneratorMethods$RbNil$INVOKER$s$0$0$to_json
I/System.out: defineClass: name: json.ext.GeneratorMethods$RbObject$INVOKER$s$0$0$to_json
I/System.out: defineClass: name: json.ext.GeneratorMethods$RbString$INVOKER$s$0$0$to_json
I/System.out: defineClass: name: json.ext.GeneratorMethods$RbString$INVOKER$s$0$0$to_json_raw
I/System.out: defineClass: name: json.ext.GeneratorMethods$RbString$INVOKER$s$0$0$to_json_raw_object
I/System.out: defineClass: name: json.ext.GeneratorMethods$RbString$INVOKER$s$1$0$included
I/System.out: defineClass: name: json.ext.GeneratorMethods$RbTrue$INVOKER$s$0$0$to_json
I/System.out: defineClass: name: json.ext.GeneratorMethods$StringExtend$INVOKER$s$1$0$json_create
I/System.out: Using Ext extension for JSON.
I/zygote: Background concurrent copying GC freed 104498(6MB) AllocSpace objects, 3(80KB) LOS objects, 14% free, 34MB/40MB, paused 452us total 128.840ms
I/zygote: Background concurrent copying GC freed 246854(8MB) AllocSpace objects, 42(852KB) LOS objects, 15% free, 32MB/38MB, paused 683us total 104.251ms
I/System.out: defineClass: name: org.jruby.gen.RubyObject4
I/System.out: defineClass: name: org.jruby.gen.RubyObject4Allocator

I/System.out: require 'active_record/base'
I/zygote: Background concurrent copying GC freed 161160(6MB) AllocSpace objects, 25(564KB) LOS objects, 14% free, 36MB/42MB, paused 772us total 149.602ms
I/zygote: Background concurrent copying GC freed 267733(9MB) AllocSpace objects, 14(320KB) LOS objects, 14% free, 36MB/42MB, paused 1.387ms total 107.485ms
I/zygote: Background concurrent copying GC freed 299560(10MB) AllocSpace objects, 3(60KB) LOS objects, 15% free, 33MB/39MB, paused 1.384ms total 102.623ms
I/System.out: defineClass: name: org.jruby.ext.psych.PsychParser$INVOKER$i$parse
I/System.out: defineClass: name: org.jruby.ext.psych.PsychParser$INVOKER$i$0$0$mark
I/System.out: defineClass: name: org.jruby.ext.psych.PsychEmitter$INVOKER$i$1$0$start_mapping
I/System.out: defineClass: name: org.jruby.ext.psych.PsychEmitter$INVOKER$i$0$0$end_sequence
I/System.out: defineClass: name: org.jruby.ext.psych.PsychEmitter$INVOKER$i$0$0$line_width
I/System.out: defineClass: name: org.jruby.ext.psych.PsychEmitter$INVOKER$i$3$0$start_document
I/System.out: defineClass: name: org.jruby.ext.psych.PsychEmitter$INVOKER$i$0$0$end_mapping
I/System.out: defineClass: name: org.jruby.ext.psych.PsychEmitter$INVOKER$i$0$0$canonical
I/System.out: defineClass: name: org.jruby.ext.psych.PsychEmitter$INVOKER$i$1$0$indentation_set
I/System.out: defineClass: name: org.jruby.ext.psych.PsychEmitter$INVOKER$i$1$0$end_document
I/System.out: defineClass: name: org.jruby.ext.psych.PsychEmitter$INVOKER$i$1$0$line_width_set
I/System.out: defineClass: name: org.jruby.ext.psych.PsychEmitter$INVOKER$i$1$0$scalar
I/System.out: defineClass: name: org.jruby.ext.psych.PsychEmitter$INVOKER$i$0$0$indentation
I/System.out: defineClass: name: org.jruby.ext.psych.PsychEmitter$INVOKER$i$1$0$start_stream
I/System.out: defineClass: name: org.jruby.ext.psych.PsychEmitter$INVOKER$i$0$0$end_stream
I/System.out: defineClass: name: org.jruby.ext.psych.PsychEmitter$INVOKER$i$1$0$alias
I/System.out: defineClass: name: org.jruby.ext.psych.PsychEmitter$INVOKER$i$1$0$start_sequence
I/System.out: defineClass: name: org.jruby.ext.psych.PsychEmitter$INVOKER$i$initialize
I/System.out: defineClass: name: org.jruby.ext.psych.PsychEmitter$INVOKER$i$1$0$canonical_set
I/zygote: Background concurrent copying GC freed 180591(6MB) AllocSpace objects, 5(100KB) LOS objects, 14% free, 35MB/41MB, paused 1.061ms total 350.387ms
I/System.out: defineClass: name: org.jruby.ext.psych.PsychToRuby$ToRuby$INVOKER$s$2$0$build_exception
I/System.out: defineClass: name: org.jruby.ext.psych.PsychToRuby$ClassLoader$INVOKER$s$1$0$path2class
I/System.out: defineClass: name: org.jruby.ext.psych.PsychYamlTree$INVOKER$s$2$0$private_iv_get
I/zygote: Background concurrent copying GC freed 176894(8MB) AllocSpace objects, 0(0B) LOS objects, 13% free, 38MB/44MB, paused 2.280ms total 189.506ms
I/zygote: Background concurrent copying GC freed 323474(11MB) AllocSpace objects, 2(40KB) LOS objects, 13% free, 37MB/43MB, paused 888us total 142.543ms
I/zygote: Background concurrent copying GC freed 296930(10MB) AllocSpace objects, 2(40KB) LOS objects, 13% free, 37MB/43MB, paused 839us total 100.226ms
I/zygote: Background concurrent copying GC freed 307327(10MB) AllocSpace objects, 1(20KB) LOS objects, 14% free, 36MB/42MB, paused 1.200ms total 129.160ms
I/zygote: Background concurrent copying GC freed 316254(11MB) AllocSpace objects, 0(0B) LOS objects, 13% free, 37MB/43MB, paused 653us total 143.527ms
I/zygote: Background concurrent copying GC freed 313288(10MB) AllocSpace objects, 0(0B) LOS objects, 13% free, 37MB/43MB, paused 718us total 128.485ms
I/zygote: Background concurrent copying GC freed 292459(10MB) AllocSpace objects, 2(40KB) LOS objects, 13% free, 38MB/44MB, paused 690us total 109.014ms
I/zygote: Background concurrent copying GC freed 304709(10MB) AllocSpace objects, 7(144KB) LOS objects, 14% free, 35MB/41MB, paused 1.018ms total 116.742ms
I/System: Loaded time zone names for "en" in 6ms (4ms in ICU)
I/zygote: Background concurrent copying GC freed 160728(6MB) AllocSpace objects, 38(760KB) LOS objects, 13% free, 37MB/43MB, paused 768us total 194.262ms
I/System.out: defineClass: name: org.jruby.gen.RubyObject5
I/System.out: defineClass: name: org.jruby.gen.RubyObject5Allocator
I/System.out: Exception `NameError' at (empty):0 - uninitialized constant PresenceValidator
I/System.out: Exception `NameError' at (empty):0 - uninitialized constant ActiveModel::PresenceValidator
I/System.out: Exception `NameError' at (empty):0 - uninitialized constant ActiveModel::Validations::PresenceValidator
I/chatty: uid=10085(u0_a85) org.ruboto.jruby9k_poc identical 5 lines
I/System.out: Exception `NameError' at (empty):0 - uninitialized constant ActiveModel::Validations::PresenceValidator
I/System.out: Exception setting up simple ActiveRecord: uninitialized constant ActiveModel::Validations::PresenceValidator
I/System.out: uri:classloader:/active_record/validations/presence.rb:3:in `<module:Validations>'
    uri:classloader:/active_record/validations/presence.rb:2:in `<module:ActiveRecord>'
    uri:classloader:/active_record/validations/presence.rb:1:in `<main>'
    /data/app/org.ruboto.jruby9k_poc-vW_b4Xny2wSF_CrZFeKx_Q==/base.apk!/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1:in `require'
I/System.out: /data/app/org.ruboto.jruby9k_poc-vW_b4Xny2wSF_CrZFeKx_Q==/base.apk!/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1:in `(root)'
    /data/app/org.ruboto.jruby9k_poc-vW_b4Xny2wSF_CrZFeKx_Q==/base.apk!/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `block in require'
    uri:classloader:/active_record/validations.rb:90:in `<class:<main>>'
    uri:classloader:/active_record/base.rb:1:in `<module:(root)>'
    uri:classloader:/active_record/base.rb:294:in `<main>'
    uri:classloader:/active_record/base.rb:269:in `require'
    uri:classloader:/active_record/base.rb:269:in `ActiveRecord'
    uri:classloader:/active_record/base.rb:26:in `block in <main>'
    /data/app/org.ruboto.jruby9k_poc-vW_b4Xny2wSF_CrZFeKx_Q==/base.apk!/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1:in `(root)'
    /data/app/org.ruboto.jruby9k_poc-vW_b4Xny2wSF_CrZFeKx_Q==/base.apk!/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require'
    uri:classloader:/setup_active_record_sqlite.rb:7:in `<main>'
    /data/app/org.ruboto.jruby9k_poc-vW_b4Xny2wSF_CrZFeKx_Q==/base.apk!/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1:in `(root)'
I/System.out: /data/app/org.ruboto.jruby9k_poc-vW_b4Xny2wSF_CrZFeKx_Q==/base.apk!/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require'
```

**Comment by donv** [comment]
@headius I was able to get past the NameError by requiring `active_model/validations/presence` from `active_record/validations/presence.rb`.  I guess this hints at a problem with AutoLoad.

**Comment by donv** [comment]
I got AR working!  I had to work around the autoload issue by adding some files under `app/src/main/resources/active_record`.  The changes are commited.

@headius could you look at the autoload issue?

**Comment by donv** [comment]
Looks like this is not ActiveRecord specific, so I'll close it and open a new issue.
